name: Frontend CI

on:
  push:
    branches: [ develop, main ]
    paths:
      - 'voter-app/**' # Trigger only when changes are made in the frontend directory
  pull_request:
    branches: [ develop ]
    paths:
      - 'voter-app/**' # Trigger only when changes are made in the frontend directory

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.2.0] # Specify the Node.js versions you want to test against

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install frontend dependencies
      run: npm install
      working-directory: ./voter-app # Specify the frontend directory

    - name: Run frontend tests
      run: npm test
      working-directory: ./voter-app # Specify the frontend directory
