name: Check Merge Source

on:
  pull_request:
    branches: [ main ]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is develop
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "Only the develop branch can be merged into main."
          exit 1
